"""Lossless JSON patch tools for Arturia MiniFreak and MicroFreak."""

from minifreak_patch.constants import (
    Osc1Engine,
    Osc2Engine,
    FxAlgorithm,
    FilterMode,
    LfoWaveform,
    LfoRetrigMode,
    LfoRateSync,
    LfoSyncFilter,
    NoteMode,
    UnisonCount,
    UnisonMode,
    PolyAlloc,
    PolySteal,
    RetrigMode,
    SeqMode,
    ArpMode,
    ArpOct,
    CycEnvMode,
    CycEnvRetrigSrc,
    CycEnvStageOrder,
    VeloAtMode,
    SeqTimeDiv,
    ModSource,
    ModCluster,
    TuneModQuantize,
)
from minifreak_patch.parser import ParseError, PresetHeader, extract_mnfx_text
from minifreak_patch.preset import MiniFreakPreset, sanitize_default_base
from minifreak_patch.recipe import Recipe, load_recipe
from minifreak_patch.microfreak import MicroFreakObject, MicroFreakPreset
from minifreak_patch.schema import (
    DeviceModel,
    PatchDocument,
    SupportLevel,
    capabilities_for,
)
from minifreak_patch.transport import (
    DirectTransportDiscovery,
    ElektroidTransport,
    WavetableWriteReport,
)
from minifreak_patch.collage import (
    CollageCodec,
    CollageFrame,
    CollageStreamDecoder,
    RetrievedResource,
    extract_collage_descriptors,
    extract_retrieved_resources,
    patch_document_from_capture,
    patch_document_from_resource,
    summarize_capture,
)
from minifreak_patch.wavetable import MicroFreakWavetable, WavetableDocument
from minifreak_patch.live import MidiControl, controls_for, send_control
from minifreak_patch.minifreak_usb import MiniFreakUsbTransport

__all__ = [
    # Core types
    "MiniFreakPreset",
    "MicroFreakPreset",
    "MicroFreakObject",
    "Recipe",
    "PatchDocument",
    "DeviceModel",
    "SupportLevel",
    "ElektroidTransport",
    "DirectTransportDiscovery",
    "WavetableWriteReport",
    "CollageCodec",
    "CollageFrame",
    "CollageStreamDecoder",
    "RetrievedResource",
    "MicroFreakWavetable",
    "WavetableDocument",
    "MidiControl",
    "MiniFreakUsbTransport",
    "ParseError",
    "PresetHeader",
    # Factory functions
    "load_recipe",
    "extract_mnfx_text",
    "sanitize_default_base",
    "capabilities_for",
    "extract_collage_descriptors",
    "extract_retrieved_resources",
    "patch_document_from_capture",
    "patch_document_from_resource",
    "summarize_capture",
    "controls_for",
    "send_control",
    # Enums
    "Osc1Engine",
    "Osc2Engine",
    "FxAlgorithm",
    "FilterMode",
    "LfoWaveform",
    "LfoRetrigMode",
    "LfoRateSync",
    "LfoSyncFilter",
    "NoteMode",
    "UnisonCount",
    "UnisonMode",
    "PolyAlloc",
    "PolySteal",
    "RetrigMode",
    "SeqMode",
    "ArpMode",
    "ArpOct",
    "CycEnvMode",
    "CycEnvRetrigSrc",
    "CycEnvStageOrder",
    "VeloAtMode",
    "SeqTimeDiv",
    "ModSource",
    "ModCluster",
    "TuneModQuantize",
]
